version: '3.8'

services:
  socket-server:
    build:
      context: ../..
      dockerfile: apps/socketServerGameHub/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped 