name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
    - name: Setup environment variables
      run: |
        echo "NODE_ENV=test" >> $GITHUB_ENV
        echo "SOCKET_URL=https://socket.stormyfocus.cloud" >> $GITHUB_ENV
    - name: Install dependencies
      run: npm ci
    - name: Generate Prisma client
      run: npm run db:generate
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npm run test:e2e --filter=@repo/gamesprout
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: apps/GameHub/playwright-report/
        retention-days: 30
